jobs:
# jobs for the provision-gke-kubernetes-cluster app

  # Job that provisions the GKE cluster
  - name: provision_gke_cluster_job
    type: runSh
    steps:
      - IN: app_gitRepo
        # manually trigger cluster provisioning
        switch: off
      - IN: gke_cliConfig
      - TASK:
        # provision the GKE cluster
        - script: . $APP_GITREPO_PATH/gitRepo/provision_gke_cluster.sh test-cluster us-central1-b

  # Job that deprovisions the GKE cluster
  - name: deprovision_gke_cluster_job
    type: runSh
    steps:
      - IN: app_gitRepo
        switch: off
      - IN: gke_cliConfig
      - IN: provision_gke_cluster_job
      - TASK:
        # deprovision the GKE cluster
        - script: . $APP_GITREPO_PATH/gitRepo/deprovision_gke_cluster.sh test-cluster us-central1-b
