jobs:

# jobs for the sample provision-gke-kubernetes-cluster app pipeline

################################

# add pipeline jobs

  # Job that provisions the GKE cluster
  - name: provision_gke_cluster_job
    type: runSh
    steps:
      - IN: app_gitRepo
        # manually trigger cluster provisioning
        switch: off
      - IN: gke_cliConfig
      - IN: central_state
      - OUT: central_state
      - TASK:
        # provision the GKE cluster
        - script: . $APP_GITREPO_PATH/gitRepo/provision_gke_cluster.sh test-cluster
        # Save cluster name to central state
        # http://docs.shippable.com/platform/tutorial/workflow/sharing-data-between-jobs/
        - script: shipctl put_resource_state central_state cluster test-cluster

  - name: deprovision_gke_cluster_job
    type: runSh
    steps:
      - IN: app_gitRepo
        switch: off
      - IN: gke_cliConfig
      - IN: provision_gke_cluster_job
      - IN: central_state
      - TASK:
        # get the cluster name from central state
        # temporary workaround for get_resource_version_key bug
        - script: |
            UP=$(shipctl get_resource_name central_state)
            RESOURCE_META=$(shipctl get_resource_meta $UP)
            RESOURCE_VERSION_FILE=$RESOURCE_META/version.json
            cluster=$(shipctl get_json_value $RESOURCE_VERSION_FILE "propertyBag.cluster")
        # - script: cluster=$(shipctl get_resource_version_key central_state cluster)
        # deprovision the GKE cluster
        - script: . $APP_GITREPO_PATH/gitRepo/deprovision_gke_cluster.sh $cluster
