resources:
# resources for the provision-gke-kubernetes-cluster app

  # GitHub repo holding scripts to be used in runsh pipeline job
  - name: app_gitRepo
    type: gitRepo
    integration: dr_github # replace with your GitHub integration name
    pointer:
      # replace with source code location (e.g. GitHub) where you cloned this
      # sample project.
      sourceName: devops-recipes/provision-gke-kubernetes-cluster
      branch: master

  # config for GKE CLI
  - name: gke_cliConfig
    type: cliConfig
    integration: drship_gcloud    # replace with your Google Cloud integration name
    pointer:
      region: us-central1-b

  - name: app_trigger
    type: trigger
    version:
      # update counter to trigger the workflow
      counter: 2


jobs:
# jobs for the provision-gke-kubernetes-cluster app

  # Job that provisions the GKE cluster
  - name: provision_gke_cluster_job
    type: runSh
    steps:
      - IN: app_gitRepo
        # manually trigger the cluster provisioning job and not on every commit to the repository
        switch: off
      - IN: gke_cliConfig
        scopes:
          - gke
      - IN: app_trigger
      - TASK:
        # invoke a script that provisions the GKE cluster named test-cluster
        - script: . $APP_GITREPO_PATH/gitRepo/provision_gke_cluster.sh test-cluster

  # Job that deprovisions the GKE cluster
  - name: deprovision_gke_cluster_job
    type: runSh
    steps:
      - IN: app_gitRepo
        switch: off
      - IN: gke_cliConfig
        scopes:
          - gke
      - IN: provision_gke_cluster_job
      - TASK:
        # invoke a script that deprovisions the GKE cluster named test-cluster
        # $GKE_CLICONFIG_POINTER_REGION is an environment variable that is automatically created and injected
        # by the gke_cliConfig resource and points to the availability zone.
        - script: . $APP_GITREPO_PATH/gitRepo/deprovision_gke_cluster.sh test-cluster $GKE_CLICONFIG_POINTER_REGION
