jobs:
# jobs for the provision-gke-kubernetes-cluster app

  # Job that provisions the GKE cluster
  - name: provision_gke_cluster_job
    type: runSh
    steps:
      - IN: app_gitRepo
        # manually trigger the cluster provisioning job and not on every commit to the repository
        switch: off
      - IN: gke_cliConfig
      - IN: app_trigger
      - TASK:
        # invoke a script that provisions the GKE cluster named test-cluster
        - script: . $APP_GITREPO_PATH/gitRepo/provision_gke_cluster.sh test-cluster

  # Job that deprovisions the GKE cluster
  - name: deprovision_gke_cluster_job
    type: runSh
    steps:
      - IN: app_gitRepo
        switch: off
      - IN: gke_cliConfig
      - IN: provision_gke_cluster_job
      - TASK:
        # invoke a script that deprovisions the GKE cluster named test-cluster
        # $GKE_CLICONFIG_POINTER_REGION is an environment variable that is automatically created and injected
        # by the gke_cliConfig resource and points to the availability zone.
        - script: . $APP_GITREPO_PATH/gitRepo/deprovision_gke_cluster.sh test-cluster $GKE_CLICONFIG_POINTER_REGION
